/**
 * Tabelle per l'abbinamento dei nomi squadra fra il foglio Sisal e le fonti dei
 * risultati (API-Football, FotMob, ESPN, SofaScore).
 *
 * PORTATE DI PESO dallo script Python di Rossi (`recupera_risultati.py`, 27/09/2026),
 * che ha gia' macinato oltre 10.000 partite vere. Ogni voce qui dentro e' stata
 * pagata con un abbinamento sbagliato trovato a mano: non vanno "migliorate" a
 * intuito.
 */

/** Sigle societarie e parole di contorno: non distinguono due squadre. */
export const STOP = new Set([
  "ac",
  "afc",
  "and",
  "as",
  "bk",
  "bsc",
  "ca",
  "calcio",
  "cd",
  "cf",
  "club",
  "cs",
  "de",
  "del",
  "e",
  "fbc",
  "fc",
  "ff",
  "fk",
  "football",
  "futbol",
  "gnk",
  "hnk",
  "if",
  "kf",
  "ks",
  "la",
  "nk",
  "ofk",
  "pfc",
  "pfk",
  "rc",
  "sc",
  "sd",
  "sk",
  "sporting",
  "ssc",
  "sv",
  "the",
  "tsv",
  "ud",
  "us",
  "vfb",
  "vfl",
  "y",
]);

/** Citta' che Sisal scrive in italiano e le fonti in lingua originale. */
export const EXONIMI: Record<string, string> = {
  "sciaffusa": "schaffhausen",
  "lucerna": "luzern",
  "basilea": "basel",
  "zurigo": "zurich",
  "losanna": "lausanne",
  "ginevra": "geneve",
  "monaco": "munich",
  "colonia": "koln",
  "magonza": "mainz",
  "norimberga": "nurnberg",
  "amburgo": "hamburg",
  "stoccarda": "stuttgart",
  "friburgo": "freiburg",
  "brema": "bremen",
  "lisbona": "lisbon",
  "siviglia": "sevilla",
  "saragozza": "zaragoza",
  "salisburgo": "salzburg",
  "vienna": "wien",
  "praga": "prague",
  "varsavia": "warsaw",
  "cracovia": "krakow",
  "bucarest": "bucharest",
  "belgrado": "belgrade",
  "atene": "athens",
  "mosca": "moscow",
};

/** Nazionali: Sisal in italiano, le fonti in inglese. */
export const NAZIONI_RAW: Record<string, string> = {
  "inghilterra": "england",
  "scozia": "scotland",
  "galles": "wales",
  "irlanda del nord": "northern ireland",
  "irlanda": "ireland",
  "rep irlanda": "ireland",
  "repubblica d irlanda": "ireland",
  "spagna": "spain",
  "francia": "france",
  "germania": "germany",
  "italia": "italy",
  "olanda": "netherlands",
  "paesi bassi": "netherlands",
  "belgio": "belgium",
  "svizzera": "switzerland",
  "austria": "austria",
  "danimarca": "denmark",
  "svezia": "sweden",
  "norvegia": "norway",
  "finlandia": "finland",
  "islanda": "iceland",
  "isole far oer": "faroe islands",
  "far oer": "faroe islands",
  "polonia": "poland",
  "repubblica ceca": "czechia",
  "rep ceca": "czechia",
  "czech republic": "czechia",
  "slovacchia": "slovakia",
  "ungheria": "hungary",
  "romania": "romania",
  "bulgaria": "bulgaria",
  "grecia": "greece",
  "turchia": "turkey",
  "turkiye": "turkey",
  "croazia": "croatia",
  "serbia": "serbia",
  "slovenia": "slovenia",
  "bosnia erzegovina": "bosnia",
  "bosnia and herzegovina": "bosnia",
  "bosnia herzegovina": "bosnia",
  "montenegro": "montenegro",
  "albania": "albania",
  "kosovo": "kosovo",
  "macedonia del nord": "macedonia",
  "macedonia": "macedonia",
  "north macedonia": "macedonia",
  "fyr macedonia": "macedonia",
  "moldavia": "moldova",
  "moldova": "moldova",
  "ucraina": "ukraine",
  "bielorussia": "belarus",
  "russia": "russia",
  "lituania": "lithuania",
  "lettonia": "latvia",
  "estonia": "estonia",
  "georgia": "georgia",
  "armenia": "armenia",
  "azerbaigian": "azerbaijan",
  "kazakistan": "kazakhstan",
  "cipro": "cyprus",
  "malta": "malta",
  "lussemburgo": "luxembourg",
  "andorra": "andorra",
  "san marino": "san marino",
  "gibilterra": "gibraltar",
  "liechtenstein": "liechtenstein",
  "israele": "israel",
  "portogallo": "portugal",
  "stati uniti": "usa",
  "united states": "usa",
  "messico": "mexico",
  "brasile": "brazil",
  "argentina": "argentina",
  "cile": "chile",
  "peru": "peru",
  "colombia": "colombia",
  "uruguay": "uruguay",
  "paraguay": "paraguay",
  "giappone": "japan",
  "corea del sud": "south korea",
  "korea republic": "south korea",
  "cina": "china",
  "australia": "australia",
  "marocco": "morocco",
  "egitto": "egypt",
  "tunisia": "tunisia",
  "algeria": "algeria",
  "senegal": "senegal",
  "nigeria": "nigeria",
  "camerun": "cameroon",
  "costa d avorio": "ivory coast",
  "cote d ivoire": "ivory coast",
  "sudafrica": "south africa",
  "arabia saudita": "saudi arabia",
  "emirati arabi uniti": "united arab emirates",
  "iran": "iran",
  "iraq": "iraq",
  "qatar": "qatar",
  "nuova zelanda": "new zealand",
  "canada": "canada",
  "zimbabwe": "zimbabwe",
  "ghana": "ghana",
  "repubblica dominicana": "dominican republic",
  "rep dominicana": "dominican republic",
  "isole cayman": "cayman islands",
  "isole vergini": "virgin islands",
  "nicaragua": "nicaragua",
  "dominica": "dominica",
  "giamaica": "jamaica",
  "haiti": "haiti",
  "cuba": "cuba",
  "honduras": "honduras",
  "guatemala": "guatemala",
  "panama": "panama",
  "el salvador": "el salvador",
  "trinidad tobago": "trinidad and tobago",
  "trinidad and tobago": "trinidad and tobago",
  "corea del nord": "north korea",
  "repubblica democratica di corea": "north korea",
  "repubblica democratica di": "north korea",
  "korea dpr": "north korea",
  "dpr korea": "north korea",
  "vietnam": "vietnam",
  "thailandia": "thailand",
  "indonesia": "indonesia",
  "malesia": "malaysia",
  "filippine": "philippines",
  "india": "india",
  "uzbekistan": "uzbekistan",
  "giordania": "jordan",
  "libano": "lebanon",
  "siria": "syria",
  "oman": "oman",
  "bahrein": "bahrain",
  "kuwait": "kuwait",
  "venezuela": "venezuela",
  "ecuador": "ecuador",
  "bolivia": "bolivia",
  "costa rica": "costa rica",
  "capo verde": "cape verde",
  "guinea equatoriale": "equatorial guinea",
  "guinea": "guinea",
  "mali": "mali",
  "burkina faso": "burkina faso",
  "rd congo": "dr congo",
  "congo dr": "dr congo",
  "zambia": "zambia",
  "kenya": "kenya",
  "tanzania": "tanzania",
  "uganda": "uganda",
  "angola": "angola",
  "libia": "libya",
  "sudan": "sudan",
  "etiopia": "ethiopia",
  "sud sudan": "south sudan",
  "santa lucia": "saint lucia",
  "saint lucia": "saint lucia",
  "malawi": "malawi",
  "barbados": "barbados",
  "grenada": "grenada",
  "bermuda": "bermuda",
  "aruba": "aruba",
  "curacao": "curacao",
  "guyana": "guyana",
  "suriname": "suriname",
  "belize": "belize",
  "mozambico": "mozambique",
  "namibia": "namibia",
  "botswana": "botswana",
  "ruanda": "rwanda",
  "benin": "benin",
  "togo": "togo",
  "gambia": "gambia",
  "niger": "niger",
  "mauritania": "mauritania",
  "madagascar": "madagascar",
  "gabon": "gabon",
  "sierra leone": "sierra leone",
  "liberia": "liberia",
  "eswatini": "eswatini",
  "lesotho": "lesotho",
  "burundi": "burundi",
  "ciad": "chad",
  "hong kong": "hong kong",
  "singapore": "singapore",
  "myanmar": "myanmar",
  "cambogia": "cambodia",
  "laos": "laos",
  "nepal": "nepal",
  "bangladesh": "bangladesh",
  "sri lanka": "sri lanka",
  "pakistan": "pakistan",
  "afghanistan": "afghanistan",
  "tagikistan": "tajikistan",
  "kirghizistan": "kyrgyzstan",
  "turkmenistan": "turkmenistan",
  "mongolia": "mongolia",
  "palestina": "palestine",
  "yemen": "yemen",
  "taipei cinese": "chinese taipei",
  "figi": "fiji",
};

/** Nomi lunghi che le fonti abbreviano in sigla. */
export const SIGLE: Record<string, string> = {
  "kuopion palloseura": "kups",
  "mikkelin palloilijat": "mp",
  "university college dublin": "ucd",
  "kokkola": "kpv",
  "kokkolan palloveikot": "kpv",
  "vaasan palloseura": "vps",
  "rovaniemen palloseura": "rops",
  "seinajoen jalkapallokerho": "sjk",
  "helsingin jalkapalloklubi": "hjk",
  "hjk helsinki": "hjk",
  "inter turku": "inter turku",
  "ifk mariehamn": "mariehamn",
};

/** Parole comuni che da sole NON bastano a dire che due squadre sono la stessa:
 *  senza questo elenco "Manchester United" e "Manchester City" si somiglierebbero. */
export const GENERICHE = new Set([
  "academy",
  "aires",
  "akatemia",
  "albion",
  "athletic",
  "atletico",
  "b",
  "buenos",
  "central",
  "city",
  "ciudad",
  "clube",
  "county",
  "deportes",
  "deportivo",
  "dinamo",
  "dynamo",
  "esporte",
  "fc",
  "gen",
  "helsinki",
  "hotspur",
  "independiente",
  "inter",
  "juventus",
  "lima",
  "mar",
  "montevideo",
  "nacional",
  "next",
  "olimpia",
  "olympic",
  "racing",
  "real",
  "reserves",
  "rio",
  "rovers",
  "saint",
  "san",
  "santa",
  "santiago",
  "santo",
  "sao",
  "sport",
  "sportif",
  "sports",
  "st",
  "stade",
  "tashkent",
  "tbilisi",
  "town",
  "u17",
  "u19",
  "u20",
  "u21",
  "u23",
  "union",
  "united",
  "universidad",
  "utd",
  "villa",
  "vina",
  "wanderers",
  "women",
]);

/** Parole che DISTINGUONO: se ce l'ha solo uno dei due nomi non e' la stessa
 *  squadra ("Irlanda" contro "Irlanda del Nord"). */
export const DISTINTIVE = new Set([
  "democratic",
  "east",
  "new",
  "nord",
  "north",
  "northern",
  "republic",
  "south",
  "sud",
  "west",
]);

/** Marcatori di giovanili e femminili: devono corrispondere su entrambi i nomi. */
export const MARK = /\b(u1[5-9]|u2[0-3]|women|wfc|femminile|donne)\b/;
